server:
  port: ${MCP_SERVER_PORT:8082}

spring:
  application:
    name: contextcore-mcp-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  # Spring AI MCP Server Configuration
  ai:
    mcp:
      server:
        name: ContextCore MCP Server
        version: 1.0.0
        description: Intelligent Development Log Management System with Semantic Search
        type: SYNC
        stdio: true
        capabilities:
          tools: true
          resources: true

# ContextCore specific configuration
contextcore:
  # SQLite configuration
  sqlite:
    path: ${CONTEXTCORE_SQLITE_PATH:./data/contextcore.db}

  # Qdrant configuration
  qdrant:
    host: ${CONTEXTCORE_QDRANT_HOST:localhost}
    port: ${CONTEXTCORE_QDRANT_PORT:6334}
    collection: ${CONTEXTCORE_QDRANT_COLLECTION:contextcore_logs}

  # Ollama configuration
  ollama:
    host: ${CONTEXTCORE_OLLAMA_HOST:localhost}
    port: ${CONTEXTCORE_OLLAMA_PORT:11434}
    model: ${CONTEXTCORE_OLLAMA_MODEL:nomic-embed-text}
    dimension: ${CONTEXTCORE_OLLAMA_DIMENSION:768}

# Logging configuration
logging:
  level:
    root: INFO
    io.github.frankli.mcp.contextcore: ${CONTEXTCORE_LOG_LEVEL:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${CONTEXTCORE_LOG_FILE:./logs/contextcore-mcp.log}

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
