version: '3.8'

services:
  postgres-mcp:
    image: russellli/postgresql-mcp-server:latest
    container_name: postgres-mcp-test
    ports:
      - "3001:3001"
    environment:
      - MCP_SERVER_PORT=3001
      - MCP_LOG_LEVEL=INFO
      - DEFAULT_POOL_SIZE=10
      - QUERY_TIMEOUT=30
    depends_on:
      - postgres-db
    networks:
      - postgres-test-network
    restart: unless-stopped

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-test-db
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-test-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-test
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@test.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres-db
    networks:
      - postgres-test-network
    restart: unless-stopped

volumes:
  postgres_test_data:

networks:
  postgres-test-network:
    driver: bridge